services:
  app:
    build: .
    container_name: symfony_app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    command: >
      bash -c "
      if [ ! -f /var/www/html/app/composer.json ]; then
        composer create-project symfony/skeleton /var/www/html/app &&
        cd /var/www/html/app &&
        composer require webapp;
      else
        cd /var/www/html/app &&
        composer install;
      fi &&
      chown -R www-data:www-data /var/www/html/app &&
      apache2-foreground
      "

  db:
    image: mysql:8.0
    container_name: symfony_db_petclinic
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
